### ISSUE TITLE
Page breaks when navigating back from feature selection

### ISSUE THREAD

**Issue by thedivtagguy** [Vonter/blr-boundaries#23] opened 2024-10-17 03:47 UTC
To replicate: 
1. Navigate to `Taluks`
2. Select `Tumukuru`
3. Try navigating back using the back button in the sidebar

In the console, we can see:

```
Uncaught (in promise) Error: Must have at least 2 geometries

Error: The feature id parameter must be provided.
```

Currently in the `search` branch

**Comment by Vonter** [comment] 2024-10-18 16:31
Thanks for reporting the bug. Looks like it is fixed with the commit you pushed in https://github.com/Vonter/blr-boundaries/commit/a54b579dd1cf14906fc6f5e22795109b2f2f2c33

If you're not able to reproduce it anymore, I'll go ahead and close this issue.

**Closed** 2024-10-19 17:37 UTC
Labels: bug
